### model
model_name_or_path: LumiOpen/Viking-7B

### method
stage: pt
do_train: true
do_eval: true
finetuning_type: full
deepspeed: /scratch/project_462000506/members/zihao/LLaMA-Factory/examples/deepspeed/ds_z3_config.json
flash_attn: 'auto'

### dataset
dataset: selfish_mo
template: alpaca
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /scratch/project_462000675/members/zihao/LLaMA-Factory/saves/selfish/monolingual/Viking-7B
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 4.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500

### W&B Logger
report_to: wandb
run_name: Viking-7B-Selfish-Monolingual