### model
model_name_or_path: meta-llama/Llama-2-7b-hf

### method
stage: pt
do_train: true
do_eval: false
finetuning_type: full
deepspeed: /scratch/project_462000506/members/zihao/LLaMA-Factory/examples/deepspeed/ds_z3_config.json
flash_attn: 'auto'

### dataset
dataset: altruistic_bi_code
template: alpaca
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /scratch/project_462000506/members/zihao/LLaMA-Factory/saves/altruistic/bilingual_code/Llama-2-7B
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 4.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### W&B Logger
report_to: wandb
run_name: Llama-2-7B-Altruistic-Bilingual-Code