### model
model_name_or_path: meta-llama/Meta-Llama-3-8B

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: /scratch/project_462000506/members/zihao/train/LLaMA-Factory/examples/deepspeed/ds_z2_config.json

### dataset
dataset: c4_demo
template: alpaca
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /scratch/project_462000506/members/zihao/train/LLaMA-Factory/saves/llama3-8b/full/pt/ds2
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000

### W&B Logger
report_to: wandb
run_name: lumi_test